from setuptools import setup

setup(
    name='naver-cafe-attendance',
    version='0.1.0',
    packages=['venv.Lib.site-packages.attr', 'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.zope.interface',
              'venv.Lib.site-packages.zope.interface.tests', 'venv.Lib.site-packages.zope.interface.common',
              'venv.Lib.site-packages.zope.interface.common.tests', 'venv.Lib.site-packages.PyQt5',
              'venv.Lib.site-packages.PyQt5.uic', 'venv.Lib.site-packages.PyQt5.uic.Loader',
              'venv.Lib.site-packages.PyQt5.uic.port_v2', 'venv.Lib.site-packages.PyQt5.uic.port_v3',
              'venv.Lib.site-packages.PyQt5.uic.Compiler', 'venv.Lib.site-packages.automat',
              'venv.Lib.site-packages.automat._test', 'venv.Lib.site-packages.blessings',
              'venv.Lib.site-packages.hyperlink', 'venv.Lib.site-packages.hyperlink.test',
              'venv.Lib.site-packages.constantly', 'venv.Lib.site-packages.exampleproj',
              'venv.Lib.site-packages.incremental', 'venv.Lib.site-packages.incremental.tests',
              'venv.Lib.site-packages.pyqt5_installer', 'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.Lib.site-packages.pip-9.0.1-py3.6.egg.pip.operations'],
    url='https://github.com/Luyin/naver-cafe-attendance.git',
    license='',
    author='Luyin',
    author_email='myraous@gmail.com',
    description='Naver 카페 자동 출석 체크'
)
